### ISSUE TITLE
Page unavailable

### ISSUE THREAD

**Issue by eruvanos** [B00M3000/Mindustry-Schematics#122]
**Describe the bug**
Page not accessable.

**To Reproduce**

1. Go to https://www.mindustryschematics.com/
2. See error

**Expected behavior**
See web page

**Screenshots**
![image](https://user-images.githubusercontent.com/9437863/132894909-5a17d1a0-ee31-4022-9942-079cf882ce83.png)

**Comment by JeanJPNM** [comment]
Working on it

**Comment by JeanJPNM** [comment]
I can't figure out what's wrong (I don't have access to the heroku server), so I'll roll back to the previous version
